### ISSUE TITLE
Scaffold admin page

### ISSUE THREAD

**Issue by lzaaldian** [lzaaldian/blog#1]
# Tasks

- [x] Scaffold admin page using `categories`
- [x] Configure dashboard page
- [x] Configure log in page
